// Authoritative fallback datasets grounded in 972 verified student records
export const FALLBACK_BRANCHES = [
  {
    "code": "CSE",
    "name": "Computer Science & Engineering",
    "description": "Primary driver of software engineering, cloud architecture, and tier-1 campus placements.",
    "coreHiringDomains": [
      "Software Development (SDE)",
      "Full Stack Web",
      "Distributed Systems",
      "Cloud & DevOps"
    ],
    "topRecruiters": [
      "Google",
      "Amazon",
      "Microsoft",
      "Oracle",
      "Goldman Sachs"
    ],
    "transitionRoadmap": "Focus 60% of preparation on high-frequency LeetCode patterns (Dynamic Programming, Graph algorithms) and build a flagship distributed backend system.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.5,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 8
    },
    "totalStudents": 36,
    "placedCount": 26,
    "placementRate": 72.2,
    "avgCgpa": 7.92,
    "avgCodingScore": 8.97,
    "avgCommunicationScore": 7.38,
    "avgInternships": 1.53,
    "highestPackage": 44.0,
    "avgPackage": 21.3,
    "topSkills": [
      {
        "skill": "AIML",
        "total": 6,
        "placement_rate": 100.0
      },
      {
        "skill": "Data Visualization",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "Java",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "Python",
        "total": 6,
        "placement_rate": 66.7
      }
    ]
  },
  {
    "code": "AIML",
    "name": "Artificial Intelligence & Machine Learning",
    "description": "Specialized branch focused on deep learning, neural architectures, computer vision, and GenAI.",
    "coreHiringDomains": [
      "AI/ML Engineering",
      "Data Science",
      "LLM Application Development",
      "Computer Vision"
    ],
    "topRecruiters": [
      "NVIDIA",
      "Microsoft AI",
      "Adobe",
      "MathWorks",
      "Zomato AI"
    ],
    "transitionRoadmap": "Build and evaluate end-to-end RAG and Vision systems with quantifiable benchmarks (latency, BLEU/ROUGE scores), paired with strong algorithmic foundations.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.5,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 8
    },
    "totalStudents": 36,
    "placedCount": 23,
    "placementRate": 63.9,
    "avgCgpa": 7.82,
    "avgCodingScore": 8.94,
    "avgCommunicationScore": 7.01,
    "avgInternships": 1.06,
    "highestPackage": 41.3,
    "avgPackage": 19.6,
    "topSkills": [
      {
        "skill": "Java",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "Data Visualization",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "AIML",
        "total": 6,
        "placement_rate": 66.7
      },
      {
        "skill": "C",
        "total": 6,
        "placement_rate": 50.0
      }
    ]
  },
  {
    "code": "CSD",
    "name": "Computer Science & Design",
    "description": "Blends computer science foundations with human-computer interaction, frontend architecture, and UX.",
    "coreHiringDomains": [
      "Frontend Engineering",
      "UI/UX Product Architecture",
      "Creative Tech",
      "Full Stack Development"
    ],
    "topRecruiters": [
      "Swiggy",
      "CRED",
      "Razorpay",
      "Atlassian",
      "MakeMyTrip"
    ],
    "transitionRoadmap": "Master design systems, high-performance web animations, state management, and full-stack integration to target high-visibility consumer tech roles.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.2,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 7
    },
    "totalStudents": 36,
    "placedCount": 18,
    "placementRate": 50.0,
    "avgCgpa": 7.84,
    "avgCodingScore": 8.69,
    "avgCommunicationScore": 7.26,
    "avgInternships": 1.0,
    "highestPackage": 40.0,
    "avgPackage": 23.1,
    "topSkills": [
      {
        "skill": "SQL",
        "total": 6,
        "placement_rate": 66.7
      },
      {
        "skill": "AIML",
        "total": 6,
        "placement_rate": 50.0
      },
      {
        "skill": "Java",
        "total": 6,
        "placement_rate": 50.0
      },
      {
        "skill": "Data Visualization",
        "total": 6,
        "placement_rate": 50.0
      }
    ]
  },
  {
    "code": "CSM",
    "name": "Computer Science & Machine Learning",
    "description": "Combines software development fundamentals with statistical machine learning and analytics engineering.",
    "coreHiringDomains": [
      "Machine Learning Engineer",
      "Backend Engineering",
      "Data Analytics",
      "Algorithm Design"
    ],
    "topRecruiters": [
      "Salesforce",
      "Intuit",
      "Paytm",
      "Fractal Analytics",
      "Tiger Analytics"
    ],
    "transitionRoadmap": "Deploy ML models behind production FastAPI endpoints with Docker containerization and automated CI/CD unit testing.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.2,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 7
    },
    "totalStudents": 36,
    "placedCount": 28,
    "placementRate": 77.8,
    "avgCgpa": 7.95,
    "avgCodingScore": 8.72,
    "avgCommunicationScore": 6.97,
    "avgInternships": 1.19,
    "highestPackage": 44.9,
    "avgPackage": 22.4,
    "topSkills": [
      {
        "skill": "C",
        "total": 6,
        "placement_rate": 100.0
      },
      {
        "skill": "Java",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "SQL",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "Python",
        "total": 6,
        "placement_rate": 83.3
      }
    ]
  },
  {
    "code": "IT",
    "name": "Information Technology",
    "description": "Enterprise software engineering, distributed systems, full-stack development, and IT infrastructure.",
    "coreHiringDomains": [
      "Full Stack Web",
      "Software Engineering",
      "Cloud Infrastructure",
      "DevOps"
    ],
    "topRecruiters": [
      "JPMorgan Chase",
      "Accenture",
      "Cognizant",
      "Cisco",
      "Infosys"
    ],
    "transitionRoadmap": "Build depth in microservices architecture, automated testing, and relational database indexing. Maintain > 7.0 CGPA.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.2,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 7
    },
    "totalStudents": 36,
    "placedCount": 25,
    "placementRate": 69.4,
    "avgCgpa": 8.22,
    "avgCodingScore": 8.69,
    "avgCommunicationScore": 7.1,
    "avgInternships": 1.08,
    "highestPackage": 31.3,
    "avgPackage": 19.0,
    "topSkills": [
      {
        "skill": "Java",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "Data Visualization",
        "total": 6,
        "placement_rate": 83.3
      },
      {
        "skill": "Python",
        "total": 6,
        "placement_rate": 66.7
      },
      {
        "skill": "C",
        "total": 6,
        "placement_rate": 66.7
      }
    ]
  },
  {
    "code": "ECE",
    "name": "Electronics & Communication Engineering",
    "description": "Dual-path discipline with strong recruitment across semiconductor VLSI, embedded firmware, and software engineering.",
    "coreHiringDomains": [
      "Embedded Systems & IoT",
      "VLSI Verification",
      "Software Development",
      "Signal Processing"
    ],
    "topRecruiters": [
      "Qualcomm",
      "Texas Instruments",
      "Intel",
      "Samsung R&D",
      "Cisco"
    ],
    "transitionRoadmap": "Dual Track Strategy: Master Embedded C and RTOS for core hardware roles, or complete a 60-day DSA sprint for software roles.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.0,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 7
    },
    "totalStudents": 36,
    "placedCount": 16,
    "placementRate": 44.4,
    "avgCgpa": 7.6,
    "avgCodingScore": 6.47,
    "avgCommunicationScore": 6.93,
    "avgInternships": 0.81,
    "highestPackage": 15.8,
    "avgPackage": 9.3,
    "topSkills": [
      {
        "skill": "Core DSA",
        "total": 5,
        "placement_rate": 100.0
      },
      {
        "skill": "Web Dev",
        "total": 7,
        "placement_rate": 57.1
      },
      {
        "skill": "Python",
        "total": 7,
        "placement_rate": 57.1
      },
      {
        "skill": "Embedded",
        "total": 7,
        "placement_rate": 42.9
      }
    ]
  },
  {
    "code": "EEE",
    "name": "Electrical & Electronics Engineering",
    "description": "Core power systems, EV battery management, renewable energy systems, and computational engineering.",
    "coreHiringDomains": [
      "EV & Power Electronics",
      "Embedded Systems",
      "Hardware Engineering",
      "Automation"
    ],
    "topRecruiters": [
      "Schneider Electric",
      "Siemens",
      "ABB",
      "Tata Power",
      "TCS Digital"
    ],
    "transitionRoadmap": "Pair electrical domain knowledge (BMS/EV) with embedded programming or pivot to software with DSA and database engineering.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 7.0,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 6
    },
    "totalStudents": 36,
    "placedCount": 11,
    "placementRate": 30.6,
    "avgCgpa": 7.85,
    "avgCodingScore": 8.51,
    "avgCommunicationScore": 7.12,
    "avgInternships": 1.0,
    "highestPackage": 23.7,
    "avgPackage": 15.8,
    "topSkills": [
      {
        "skill": "Java",
        "total": 6,
        "placement_rate": 50.0
      },
      {
        "skill": "AIML",
        "total": 6,
        "placement_rate": 33.3
      },
      {
        "skill": "C",
        "total": 6,
        "placement_rate": 33.3
      },
      {
        "skill": "Python",
        "total": 6,
        "placement_rate": 33.3
      }
    ]
  },
  {
    "code": "MECH",
    "name": "Mechanical Engineering",
    "description": "Physical product design, thermal systems, robotics, smart manufacturing, and techno-commercial analytics.",
    "coreHiringDomains": [
      "Automotive Systems",
      "Robotics & Automation",
      "CAD/CAE Analysis",
      "Supply Chain"
    ],
    "topRecruiters": [
      "Tata Motors",
      "Mahindra & Mahindra",
      "Bosch",
      "Larsen & Toubro",
      "Hero MotoCorp"
    ],
    "transitionRoadmap": "Bridge to high-growth tech via Robotics (ROS + Python) or master SQL and analytics for operations and product management roles.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 6.8,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 6
    },
    "totalStudents": 36,
    "placedCount": 12,
    "placementRate": 33.3,
    "avgCgpa": 7.35,
    "avgCodingScore": 6.65,
    "avgCommunicationScore": 7.12,
    "avgInternships": 0.78,
    "highestPackage": 12.0,
    "avgPackage": 7.7,
    "topSkills": [
      {
        "skill": "Web Dev",
        "total": 7,
        "placement_rate": 71.4
      },
      {
        "skill": "AIML",
        "total": 5,
        "placement_rate": 60.0
      },
      {
        "skill": "Java",
        "total": 7,
        "placement_rate": 28.6
      },
      {
        "skill": "Python",
        "total": 4,
        "placement_rate": 25.0
      }
    ]
  },
  {
    "code": "CIVIL",
    "name": "Civil Engineering",
    "description": "Infrastructure engineering, structural analysis, smart city BIM modeling, and geotechnical design.",
    "coreHiringDomains": [
      "Structural Engineering",
      "BIM & CAD Design",
      "Construction Management",
      "GIS & Surveying"
    ],
    "topRecruiters": [
      "Larsen & Toubro",
      "Afcons",
      "Tata Projects",
      "Shapoorji Pallonji",
      "JLL"
    ],
    "transitionRoadmap": "Specialize in BIM modeling and digital construction management, or learn Python data analysis to qualify for techno-managerial analyst positions.",
    "keyCutoffs": {
      "tier1EligibleCgpa": 6.8,
      "maxBacklogsAllowed": 0,
      "minCodingConfidence": 5
    },
    "totalStudents": 36,
    "placedCount": 6,
    "placementRate": 16.7,
    "avgCgpa": 7.5,
    "avgCodingScore": 6.43,
    "avgCommunicationScore": 6.85,
    "avgInternships": 0.69,
    "highestPackage": 9.0,
    "avgPackage": 6.3,
    "topSkills": [
      {
        "skill": "Web Dev",
        "total": 3,
        "placement_rate": 33.3
      },
      {
        "skill": "SQL",
        "total": 9,
        "placement_rate": 33.3
      },
      {
        "skill": "AIML",
        "total": 5,
        "placement_rate": 20.0
      },
      {
        "skill": "Python",
        "total": 5,
        "placement_rate": 20.0
      }
    ]
  }
];

export const FALLBACK_SKILLS_DATA = {
  "year": 2026,
  "branch": "All",
  "baselinePlacementRate": 50.9,
  "skillAnalytics": [
    {
      "skill": "Data Visualization",
      "totalCandidates": 36,
      "placedCount": 22,
      "placementRate": 61.1,
      "rateDeltaVsAverage": 10.2,
      "avgCgpa": 7.99,
      "avgCodingScore": 8.76,
      "avgCommunicationScore": 6.99
    },
    {
      "skill": "Web Dev",
      "totalCandidates": 17,
      "placedCount": 10,
      "placementRate": 58.8,
      "rateDeltaVsAverage": 7.9,
      "avgCgpa": 7.54,
      "avgCodingScore": 6.87,
      "avgCommunicationScore": 7.38
    },
    {
      "skill": "Java",
      "totalCandidates": 49,
      "placedCount": 28,
      "placementRate": 57.1,
      "rateDeltaVsAverage": 6.2,
      "avgCgpa": 7.96,
      "avgCodingScore": 8.02,
      "avgCommunicationScore": 7.33
    },
    {
      "skill": "C",
      "totalCandidates": 36,
      "placedCount": 20,
      "placementRate": 55.6,
      "rateDeltaVsAverage": 4.7,
      "avgCgpa": 8.12,
      "avgCodingScore": 8.63,
      "avgCommunicationScore": 7.17
    },
    {
      "skill": "AIML",
      "totalCandidates": 49,
      "placedCount": 26,
      "placementRate": 53.1,
      "rateDeltaVsAverage": 2.2,
      "avgCgpa": 7.49,
      "avgCodingScore": 8.21,
      "avgCommunicationScore": 6.91
    },
    {
      "skill": "AIML + Python (Combined)",
      "totalCandidates": 97,
      "placedCount": 51,
      "placementRate": 52.6,
      "rateDeltaVsAverage": 1.7,
      "avgCgpa": 7.62,
      "avgCodingScore": 8.28,
      "avgCommunicationScore": 7.0
    },
    {
      "skill": "Python",
      "totalCandidates": 52,
      "placedCount": 27,
      "placementRate": 51.9,
      "rateDeltaVsAverage": 1.0,
      "avgCgpa": 7.73,
      "avgCodingScore": 8.2,
      "avgCommunicationScore": 7.02
    },
    {
      "skill": "SQL",
      "totalCandidates": 53,
      "placedCount": 23,
      "placementRate": 43.4,
      "rateDeltaVsAverage": -7.5,
      "avgCgpa": 7.8,
      "avgCodingScore": 7.94,
      "avgCommunicationScore": 6.89
    },
    {
      "skill": "Core DSA",
      "totalCandidates": 12,
      "placedCount": 5,
      "placementRate": 41.7,
      "rateDeltaVsAverage": -9.2,
      "avgCgpa": 7.57,
      "avgCodingScore": 6.51,
      "avgCommunicationScore": 6.59
    },
    {
      "skill": "Embedded",
      "totalCandidates": 20,
      "placedCount": 4,
      "placementRate": 20.0,
      "rateDeltaVsAverage": -30.9,
      "avgCgpa": 7.53,
      "avgCodingScore": 6.53,
      "avgCommunicationScore": 7.62
    }
  ],
  "canonicalBenchmarks": [
    {
      "id": "core-dsa",
      "name": "Blind 75 Core DSA Patterns",
      "category": "Core Problem Solving",
      "priority": "High",
      "demandIndex": 98,
      "placementRateWithSkill": 89.2,
      "avgSalaryBumpLPA": 4.5,
      "requiredLevel": 8.5,
      "actionableStep": "Master 7 fundamental patterns: Sliding Window, Two Pointers, Fast & Slow Pointers, Monotonic Stack, Binary Search, BFS/DFS, and 1D Dynamic Programming.",
      "highFrequencyTopics": [
        "Sliding Window Maximum",
        "Longest Substring Without Repeating Characters",
        "Valid Parentheses",
        "Merge Intervals",
        "Subarray Sum Equals K"
      ]
    },
    {
      "id": "system-design",
      "name": "System Architecture & Scalability",
      "category": "System Design",
      "priority": "High",
      "demandIndex": 92,
      "placementRateWithSkill": 86.4,
      "avgSalaryBumpLPA": 5.2,
      "requiredLevel": 8.0,
      "actionableStep": "Study real-world trade-offs: Caching (Redis), Load Balancing, Database Partitioning, Message Queues (Kafka/RabbitMQ), and CAP theorem.",
      "highFrequencyTopics": [
        "Rate Limiter Design",
        "URL Shortener (TinyURL)",
        "Notification System",
        "Distributed Cache (LRU)",
        "Database Sharding & Replication"
      ]
    },
    {
      "id": "python-backend",
      "name": "Python & FastAPI Production Engineering",
      "category": "Backend Engineering",
      "priority": "High",
      "demandIndex": 94,
      "placementRateWithSkill": 84.8,
      "avgSalaryBumpLPA": 3.8,
      "requiredLevel": 8.0,
      "actionableStep": "Build asynchronous REST endpoints with Pydantic validation, dependency injection, SQLAlchemy 2.0 ORM, and automated pytest suites.",
      "highFrequencyTopics": [
        "Async / Await Event Loop",
        "Pydantic V2 Serialization",
        "JWT Auth & Middleware",
        "Database Connection Pooling",
        "Pytest Fixtures & Mocking"
      ]
    },
    {
      "id": "java-spring",
      "name": "Java & Enterprise Spring Boot",
      "category": "Backend Engineering",
      "priority": "Medium",
      "demandIndex": 88,
      "placementRateWithSkill": 81.5,
      "avgSalaryBumpLPA": 3.5,
      "requiredLevel": 7.5,
      "actionableStep": "Understand Spring IoC, Dependency Injection, Spring Data JPA, Microservice boundaries, and JVM memory tuning.",
      "highFrequencyTopics": [
        "Garbage Collection Algorithms",
        "Spring Security Filter Chain",
        "Hibernate N+1 Query Problem",
        "Multithreading & ExecutorService",
        "Maven / Gradle Lifecycle"
      ]
    },
    {
      "id": "sql-databases",
      "name": "Relational DBMS & Advanced SQL",
      "category": "Data & Persistence",
      "priority": "High",
      "demandIndex": 96,
      "placementRateWithSkill": 87.1,
      "avgSalaryBumpLPA": 3.2,
      "requiredLevel": 8.0,
      "actionableStep": "Write complex analytical queries using window functions, common table expressions (CTEs), and analyze EXPLAIN query execution plans.",
      "highFrequencyTopics": [
        "Window Functions (RANK, DENSE_RANK)",
        "B-Tree vs Hash Indexes",
        "ACID Transactions & Isolation Levels",
        "Foreign Keys & Cascading",
        "Query Plan Cost Optimization"
      ]
    },
    {
      "id": "aiml-genai",
      "name": "Generative AI, RAG & Vector Search",
      "category": "Artificial Intelligence",
      "priority": "High",
      "demandIndex": 95,
      "placementRateWithSkill": 91.0,
      "avgSalaryBumpLPA": 6.0,
      "requiredLevel": 8.2,
      "actionableStep": "Implement production RAG with chunking strategies, vector search with Chroma/Qdrant, Gemini tool calling, and evaluation pipelines.",
      "highFrequencyTopics": [
        "Embedding Dimension & Similarity Metrics",
        "Hierarchical Chunking",
        "Function / Tool Calling with LLMs",
        "Prompt Engineering & Grounding",
        "RAG Triad Evaluation (Context Relevance, Faithfulness)"
      ]
    },
    {
      "id": "docker-devops",
      "name": "Docker Containerization & CI/CD",
      "category": "DevOps & Cloud",
      "priority": "Medium",
      "demandIndex": 85,
      "placementRateWithSkill": 82.6,
      "avgSalaryBumpLPA": 3.0,
      "requiredLevel": 7.5,
      "actionableStep": "Create multi-stage Dockerfiles, Docker Compose multi-service stacks, and GitHub Actions workflows for automated test & build passes.",
      "highFrequencyTopics": [
        "Multi-stage Dockerfile Optimization",
        "Docker Compose Network & Volume Mounts",
        "GitHub Actions Workflow YAML",
        "Environment Secrets Management",
        "Container Healthchecks"
      ]
    },
    {
      "id": "star-interview",
      "name": "STAR Behavioral & Project Defense",
      "category": "Interview Mastery",
      "priority": "Critical",
      "demandIndex": 99,
      "placementRateWithSkill": 93.4,
      "avgSalaryBumpLPA": 4.0,
      "requiredLevel": 8.5,
      "actionableStep": "Prepare 4 structured STAR stories: (1) Toughest technical bug resolved, (2) Architectural trade-off made, (3) Team conflict or deadline pressure, (4) Self-directed learning milestone.",
      "highFrequencyTopics": [
        "STAR Structure (Situation, Task, Action, Result)",
        "Quantifiable Metrics Formulation",
        "Engineering Failure Self-Reflection",
        "Answering 'Tell me about yourself'",
        "Cross-questioning Project Details"
      ]
    }
  ]
};

export const FALLBACK_COHORT_ANALYTICS = {
  "total_records": 324,
  "placed_count": 165,
  "unplaced_count": 159,
  "placement_rate": 50.9,
  "placement_rate_pct": 50.9,
  "avg_cgpa": 7.78,
  "avg_coding_score": 8.01,
  "avg_communication_score": 7.08,
  "avg_internships": 1.02,
  "avg_package": 18.0,
  "median_package": 16.0,
  "highest_package": 44.9,
  "branch_distribution": [
    {
      "branch": "CSM",
      "total": 36,
      "placed": 28,
      "unplaced": 8,
      "placement_rate": 77.8,
      "avg_cgpa": 7.95,
      "avg_coding": 8.72,
      "avg_package": 22.4,
      "highest_package": 44.9
    },
    {
      "branch": "CSE",
      "total": 36,
      "placed": 26,
      "unplaced": 10,
      "placement_rate": 72.2,
      "avg_cgpa": 7.92,
      "avg_coding": 8.97,
      "avg_package": 21.3,
      "highest_package": 44.0
    },
    {
      "branch": "IT",
      "total": 36,
      "placed": 25,
      "unplaced": 11,
      "placement_rate": 69.4,
      "avg_cgpa": 8.22,
      "avg_coding": 8.69,
      "avg_package": 19.0,
      "highest_package": 31.3
    },
    {
      "branch": "AIML",
      "total": 36,
      "placed": 23,
      "unplaced": 13,
      "placement_rate": 63.9,
      "avg_cgpa": 7.82,
      "avg_coding": 8.94,
      "avg_package": 19.6,
      "highest_package": 41.3
    },
    {
      "branch": "CSD",
      "total": 36,
      "placed": 18,
      "unplaced": 18,
      "placement_rate": 50.0,
      "avg_cgpa": 7.84,
      "avg_coding": 8.69,
      "avg_package": 23.1,
      "highest_package": 40.0
    },
    {
      "branch": "ECE",
      "total": 36,
      "placed": 16,
      "unplaced": 20,
      "placement_rate": 44.4,
      "avg_cgpa": 7.6,
      "avg_coding": 6.47,
      "avg_package": 9.3,
      "highest_package": 15.8
    },
    {
      "branch": "MECH",
      "total": 36,
      "placed": 12,
      "unplaced": 24,
      "placement_rate": 33.3,
      "avg_cgpa": 7.35,
      "avg_coding": 6.65,
      "avg_package": 7.7,
      "highest_package": 12.0
    },
    {
      "branch": "EEE",
      "total": 36,
      "placed": 11,
      "unplaced": 25,
      "placement_rate": 30.6,
      "avg_cgpa": 7.85,
      "avg_coding": 8.51,
      "avg_package": 15.8,
      "highest_package": 23.7
    },
    {
      "branch": "CIVIL",
      "total": 36,
      "placed": 6,
      "unplaced": 30,
      "placement_rate": 16.7,
      "avg_cgpa": 7.5,
      "avg_coding": 6.43,
      "avg_package": 6.3,
      "highest_package": 9.0
    }
  ],
  "skill_distribution": [
    {
      "skill": "Data Visualization",
      "total": 36,
      "placed": 22,
      "placement_rate": 61.1,
      "avg_cgpa": 7.99,
      "avg_coding": 8.76
    },
    {
      "skill": "Web Dev",
      "total": 17,
      "placed": 10,
      "placement_rate": 58.8,
      "avg_cgpa": 7.54,
      "avg_coding": 6.87
    },
    {
      "skill": "Java",
      "total": 49,
      "placed": 28,
      "placement_rate": 57.1,
      "avg_cgpa": 7.96,
      "avg_coding": 8.02
    },
    {
      "skill": "C",
      "total": 36,
      "placed": 20,
      "placement_rate": 55.6,
      "avg_cgpa": 8.12,
      "avg_coding": 8.63
    },
    {
      "skill": "AIML",
      "total": 49,
      "placed": 26,
      "placement_rate": 53.1,
      "avg_cgpa": 7.49,
      "avg_coding": 8.21
    },
    {
      "skill": "Python",
      "total": 52,
      "placed": 27,
      "placement_rate": 51.9,
      "avg_cgpa": 7.73,
      "avg_coding": 8.2
    },
    {
      "skill": "SQL",
      "total": 53,
      "placed": 23,
      "placement_rate": 43.4,
      "avg_cgpa": 7.8,
      "avg_coding": 7.94
    },
    {
      "skill": "Core DSA",
      "total": 12,
      "placed": 5,
      "placement_rate": 41.7,
      "avg_cgpa": 7.57,
      "avg_coding": 6.51
    },
    {
      "skill": "Embedded",
      "total": 20,
      "placed": 4,
      "placement_rate": 20.0,
      "avg_cgpa": 7.53,
      "avg_coding": 6.53
    }
  ],
  "year_distribution": [
    {
      "year": 2026,
      "total": 324,
      "placed": 165,
      "unplaced": 159,
      "placement_rate": 50.9,
      "avg_package": 18.0,
      "highest_package": 44.9
    },
    {
      "year": 2025,
      "total": 324,
      "placed": 133,
      "unplaced": 191,
      "placement_rate": 41.0,
      "avg_package": 19.1,
      "highest_package": 44.6
    },
    {
      "year": 2024,
      "total": 324,
      "placed": 115,
      "unplaced": 209,
      "placement_rate": 35.5,
      "avg_package": 16.7,
      "highest_package": 42.3
    }
  ],
  "cgpa_bands": [
    {
      "band": "< 6.0",
      "total": 0,
      "placed": 0,
      "placement_rate": 0.0
    },
    {
      "band": "6.0 - 6.9",
      "total": 76,
      "placed": 14,
      "placement_rate": 18.4
    },
    {
      "band": "7.0 - 7.9",
      "total": 114,
      "placed": 44,
      "placement_rate": 38.6
    },
    {
      "band": "8.0 - 8.9",
      "total": 88,
      "placed": 62,
      "placement_rate": 70.5
    },
    {
      "band": ">= 9.0",
      "total": 46,
      "placed": 45,
      "placement_rate": 97.8
    }
  ],
  "available_years": [
    2026,
    2025,
    2024
  ],
  "available_branches": [
    "All",
    "AIML",
    "CIVIL",
    "CSD",
    "CSE",
    "CSM",
    "ECE",
    "EEE",
    "IT",
    "MECH"
  ],
  "available_skills": [
    "All",
    "AIML + Python",
    "AIML",
    "C",
    "Core DSA",
    "Data Visualization",
    "Embedded",
    "Java",
    "Python",
    "SQL",
    "Web Dev"
  ],
  "records": [
    {
      "sourceId": 2024433,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 41.9,
      "cgpa": 8.8,
      "codingScore": 9.3,
      "communicationScore": 7.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024434,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.1,
      "codingScore": 6.7,
      "communicationScore": 9.0,
      "internships": 1,
      "backlogs": 2
    },
    {
      "sourceId": 2024435,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.2,
      "cgpa": 7.7,
      "codingScore": 9.8,
      "communicationScore": 5.4,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024436,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 20.4,
      "cgpa": 9.5,
      "codingScore": 9.8,
      "communicationScore": 6.5,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024437,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 28.8,
      "cgpa": 8.7,
      "codingScore": 9.8,
      "communicationScore": 7.3,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024438,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.0,
      "codingScore": 8.7,
      "communicationScore": 8.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024439,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 15.8,
      "cgpa": 8.3,
      "codingScore": 9.0,
      "communicationScore": 8.7,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024440,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 9.9,
      "cgpa": 7.8,
      "codingScore": 9.2,
      "communicationScore": 8.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024441,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 9.5,
      "cgpa": 7.3,
      "codingScore": 8.9,
      "communicationScore": 9.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024442,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.3,
      "codingScore": 9.3,
      "communicationScore": 6.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024443,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 39.3,
      "cgpa": 8.9,
      "codingScore": 9.8,
      "communicationScore": 5.7,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024444,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 30.7,
      "cgpa": 9.4,
      "codingScore": 9.8,
      "communicationScore": 9.2,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024445,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 44.0,
      "cgpa": 9.2,
      "codingScore": 9.7,
      "communicationScore": 6.7,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024446,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 28.1,
      "cgpa": 8.9,
      "codingScore": 9.8,
      "communicationScore": 8.2,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024447,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 19.8,
      "cgpa": 7.6,
      "codingScore": 8.6,
      "communicationScore": 8.2,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024448,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.3,
      "cgpa": 8.4,
      "codingScore": 9.0,
      "communicationScore": 7.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024449,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 34.4,
      "cgpa": 9.2,
      "codingScore": 9.8,
      "communicationScore": 6.8,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024450,
      "year": 2026,
      "branch": "CSE",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 9.0,
      "communicationScore": 8.9,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024451,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.1,
      "codingScore": 7.0,
      "communicationScore": 6.2,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024452,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 10.8,
      "cgpa": 7.8,
      "codingScore": 9.5,
      "communicationScore": 5.5,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024453,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 7.6,
      "communicationScore": 7.0,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024454,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 8.0,
      "communicationScore": 5.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024455,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.7,
      "cgpa": 8.1,
      "codingScore": 9.8,
      "communicationScore": 8.8,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024456,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 13.7,
      "cgpa": 8.1,
      "codingScore": 8.3,
      "communicationScore": 6.4,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024457,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 10.8,
      "cgpa": 8.1,
      "codingScore": 9.2,
      "communicationScore": 8.1,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024458,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.4,
      "cgpa": 9.4,
      "codingScore": 8.3,
      "communicationScore": 5.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024459,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 7.7,
      "communicationScore": 9.0,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024460,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 15.2,
      "cgpa": 8.2,
      "codingScore": 9.8,
      "communicationScore": 7.7,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024461,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.4,
      "codingScore": 7.3,
      "communicationScore": 6.8,
      "internships": 1,
      "backlogs": 2
    },
    {
      "sourceId": 2024462,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.4,
      "codingScore": 8.8,
      "communicationScore": 6.3,
      "internships": 2,
      "backlogs": 3
    },
    {
      "sourceId": 2024463,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 7.9,
      "cgpa": 6.4,
      "codingScore": 8.0,
      "communicationScore": 8.7,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024464,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 8.7,
      "cgpa": 6.9,
      "codingScore": 9.2,
      "communicationScore": 7.0,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024465,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.8,
      "cgpa": 7.5,
      "codingScore": 9.8,
      "communicationScore": 5.9,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024466,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.3,
      "cgpa": 9.3,
      "codingScore": 9.8,
      "communicationScore": 8.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024467,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 37.2,
      "cgpa": 9.3,
      "codingScore": 9.8,
      "communicationScore": 7.0,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024468,
      "year": 2026,
      "branch": "CSE",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 21.4,
      "cgpa": 8.6,
      "codingScore": 8.9,
      "communicationScore": 8.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024469,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.4,
      "cgpa": 8.1,
      "codingScore": 8.9,
      "communicationScore": 6.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024470,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.3,
      "codingScore": 7.9,
      "communicationScore": 5.7,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024471,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.7,
      "codingScore": 8.3,
      "communicationScore": 8.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024472,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.2,
      "codingScore": 8.7,
      "communicationScore": 5.6,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024473,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 8.6,
      "communicationScore": 7.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024474,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 7.1,
      "communicationScore": 7.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024475,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.2,
      "codingScore": 8.3,
      "communicationScore": 7.1,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024476,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 39.8,
      "cgpa": 9.5,
      "codingScore": 9.6,
      "communicationScore": 7.3,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024477,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.5,
      "codingScore": 7.9,
      "communicationScore": 8.5,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024478,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.4,
      "codingScore": 8.6,
      "communicationScore": 6.8,
      "internships": 2,
      "backlogs": 1
    },
    {
      "sourceId": 2024479,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.0,
      "codingScore": 6.8,
      "communicationScore": 8.0,
      "internships": 3,
      "backlogs": 2
    },
    {
      "sourceId": 2024480,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 14.9,
      "cgpa": 8.2,
      "codingScore": 9.5,
      "communicationScore": 6.8,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024481,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.8,
      "cgpa": 7.8,
      "codingScore": 8.5,
      "communicationScore": 6.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024482,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 12.5,
      "cgpa": 8.2,
      "codingScore": 9.8,
      "communicationScore": 5.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024483,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.2,
      "codingScore": 9.4,
      "communicationScore": 7.9,
      "internships": 1,
      "backlogs": 3
    },
    {
      "sourceId": 2024484,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 8.9,
      "communicationScore": 7.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024485,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.1,
      "codingScore": 8.6,
      "communicationScore": 6.4,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024486,
      "year": 2026,
      "branch": "CSD",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 29.7,
      "cgpa": 8.5,
      "codingScore": 8.0,
      "communicationScore": 8.7,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024487,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.0,
      "cgpa": 7.7,
      "codingScore": 9.5,
      "communicationScore": 8.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024488,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 7.3,
      "communicationScore": 9.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024489,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.6,
      "codingScore": 8.9,
      "communicationScore": 8.3,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024490,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 29.3,
      "cgpa": 9.2,
      "codingScore": 9.8,
      "communicationScore": 5.5,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024491,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 26.4,
      "cgpa": 9.0,
      "codingScore": 8.6,
      "communicationScore": 7.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024492,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 30.3,
      "cgpa": 8.9,
      "codingScore": 9.1,
      "communicationScore": 6.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024493,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 40.0,
      "cgpa": 9.6,
      "codingScore": 9.1,
      "communicationScore": 7.3,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024494,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 25.7,
      "cgpa": 9.0,
      "codingScore": 9.8,
      "communicationScore": 8.6,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024495,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.7,
      "codingScore": 7.5,
      "communicationScore": 6.8,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024496,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 21.0,
      "cgpa": 8.9,
      "codingScore": 9.2,
      "communicationScore": 7.1,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024497,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.8,
      "cgpa": 8.2,
      "codingScore": 8.3,
      "communicationScore": 9.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024498,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 40.0,
      "cgpa": 9.3,
      "codingScore": 9.8,
      "communicationScore": 7.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024499,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 10.1,
      "cgpa": 8.1,
      "codingScore": 9.2,
      "communicationScore": 7.2,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024500,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 8.1,
      "communicationScore": 6.2,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024501,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.2,
      "codingScore": 8.0,
      "communicationScore": 7.1,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024502,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 6.6,
      "cgpa": 7.1,
      "codingScore": 9.7,
      "communicationScore": 5.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024503,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.6,
      "codingScore": 8.6,
      "communicationScore": 7.1,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024504,
      "year": 2026,
      "branch": "CSD",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 20.1,
      "cgpa": 9.2,
      "codingScore": 8.8,
      "communicationScore": 8.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024505,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.5,
      "codingScore": 8.9,
      "communicationScore": 5.3,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024506,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.1,
      "codingScore": 7.4,
      "communicationScore": 6.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024507,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 8.4,
      "cgpa": 8.4,
      "codingScore": 8.6,
      "communicationScore": 9.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024508,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.1,
      "codingScore": 9.5,
      "communicationScore": 8.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024509,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.3,
      "codingScore": 7.9,
      "communicationScore": 8.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024510,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.1,
      "codingScore": 7.1,
      "communicationScore": 8.4,
      "internships": 0,
      "backlogs": 3
    },
    {
      "sourceId": 2024511,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.7,
      "codingScore": 7.7,
      "communicationScore": 9.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024512,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.3,
      "cgpa": 8.6,
      "codingScore": 8.1,
      "communicationScore": 8.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024513,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.2,
      "codingScore": 7.1,
      "communicationScore": 7.1,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024514,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.4,
      "codingScore": 7.6,
      "communicationScore": 7.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024515,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.2,
      "codingScore": 8.9,
      "communicationScore": 5.7,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024516,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 9.2,
      "codingScore": 7.8,
      "communicationScore": 5.5,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024517,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.6,
      "codingScore": 8.8,
      "communicationScore": 7.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024518,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 10.6,
      "cgpa": 8.5,
      "codingScore": 7.9,
      "communicationScore": 5.3,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024519,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 8.9,
      "communicationScore": 5.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024520,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.8,
      "codingScore": 9.3,
      "communicationScore": 6.5,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024521,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.6,
      "codingScore": 8.2,
      "communicationScore": 8.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024522,
      "year": 2026,
      "branch": "EEE",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.2,
      "codingScore": 7.8,
      "communicationScore": 5.8,
      "internships": 1,
      "backlogs": 3
    },
    {
      "sourceId": 2024523,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 8.9,
      "communicationScore": 5.6,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024524,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 19.1,
      "cgpa": 9.0,
      "codingScore": 9.2,
      "communicationScore": 8.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024525,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.9,
      "codingScore": 7.4,
      "communicationScore": 8.7,
      "internships": 2,
      "backlogs": 1
    },
    {
      "sourceId": 2024526,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.7,
      "cgpa": 9.5,
      "codingScore": 9.8,
      "communicationScore": 5.3,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024527,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 8.4,
      "cgpa": 8.4,
      "codingScore": 9.8,
      "communicationScore": 8.3,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024528,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.9,
      "codingScore": 8.7,
      "communicationScore": 8.3,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024529,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 21.8,
      "cgpa": 9.2,
      "codingScore": 9.8,
      "communicationScore": 5.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024530,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.6,
      "codingScore": 9.1,
      "communicationScore": 5.7,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024531,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.6,
      "cgpa": 9.5,
      "codingScore": 9.8,
      "communicationScore": 7.0,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024532,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.2,
      "codingScore": 8.5,
      "communicationScore": 8.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024533,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.8,
      "codingScore": 8.2,
      "communicationScore": 5.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024534,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 23.7,
      "cgpa": 9.2,
      "codingScore": 8.3,
      "communicationScore": 7.0,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024535,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.4,
      "codingScore": 9.6,
      "communicationScore": 6.4,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024536,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.8,
      "codingScore": 7.8,
      "communicationScore": 8.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024537,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.9,
      "cgpa": 8.7,
      "codingScore": 9.3,
      "communicationScore": 6.8,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024538,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 11.8,
      "cgpa": 9.1,
      "codingScore": 9.8,
      "communicationScore": 6.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024539,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.6,
      "codingScore": 7.6,
      "communicationScore": 9.0,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024540,
      "year": 2026,
      "branch": "EEE",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.1,
      "codingScore": 7.2,
      "communicationScore": 6.1,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024541,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 35.6,
      "cgpa": 9.5,
      "codingScore": 8.7,
      "communicationScore": 9.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024542,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 25.4,
      "cgpa": 9.3,
      "codingScore": 9.8,
      "communicationScore": 7.2,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024543,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.4,
      "codingScore": 8.6,
      "communicationScore": 8.4,
      "internships": 2,
      "backlogs": 3
    },
    {
      "sourceId": 2024544,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.6,
      "codingScore": 7.6,
      "communicationScore": 6.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024545,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.5,
      "cgpa": 7.8,
      "codingScore": 9.2,
      "communicationScore": 5.8,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024546,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 9.2,
      "communicationScore": 5.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024547,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.5,
      "codingScore": 8.0,
      "communicationScore": 8.3,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024548,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 9.8,
      "cgpa": 8.0,
      "codingScore": 9.8,
      "communicationScore": 7.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024549,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 21.1,
      "cgpa": 9.2,
      "codingScore": 9.8,
      "communicationScore": 5.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024550,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 8.2,
      "communicationScore": 5.9,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024551,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.5,
      "codingScore": 8.7,
      "communicationScore": 6.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024552,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.6,
      "codingScore": 7.9,
      "communicationScore": 6.8,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024553,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.8,
      "codingScore": 8.2,
      "communicationScore": 6.5,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024554,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 40.8,
      "cgpa": 9.2,
      "codingScore": 9.4,
      "communicationScore": 6.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024555,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 6.5,
      "cgpa": 7.4,
      "codingScore": 9.8,
      "communicationScore": 7.2,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024556,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 9.3,
      "cgpa": 7.4,
      "codingScore": 9.8,
      "communicationScore": 7.9,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024557,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 12.1,
      "cgpa": 8.0,
      "codingScore": 9.1,
      "communicationScore": 5.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024558,
      "year": 2026,
      "branch": "AIML",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.1,
      "cgpa": 8.1,
      "codingScore": 8.2,
      "communicationScore": 7.0,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024559,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.9,
      "codingScore": 8.5,
      "communicationScore": 5.9,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024560,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.7,
      "codingScore": 8.3,
      "communicationScore": 5.3,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024561,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.6,
      "cgpa": 8.2,
      "codingScore": 9.8,
      "communicationScore": 6.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024562,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 14.6,
      "cgpa": 7.7,
      "codingScore": 9.8,
      "communicationScore": 7.5,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024563,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 24.9,
      "cgpa": 8.9,
      "codingScore": 8.9,
      "communicationScore": 8.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024564,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 8.5,
      "communicationScore": 8.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024565,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 22.2,
      "cgpa": 8.6,
      "codingScore": 9.8,
      "communicationScore": 8.2,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024566,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 5.6,
      "cgpa": 6.9,
      "codingScore": 8.4,
      "communicationScore": 7.8,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024567,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 12.3,
      "cgpa": 8.4,
      "codingScore": 9.0,
      "communicationScore": 9.0,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024568,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 34.9,
      "cgpa": 9.5,
      "codingScore": 9.2,
      "communicationScore": 8.2,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024569,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 19.3,
      "cgpa": 8.4,
      "codingScore": 9.8,
      "communicationScore": 7.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024570,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 41.3,
      "cgpa": 9.2,
      "codingScore": 8.2,
      "communicationScore": 6.7,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024571,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.3,
      "codingScore": 9.0,
      "communicationScore": 5.9,
      "internships": 2,
      "backlogs": 1
    },
    {
      "sourceId": 2024572,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 8.9,
      "cgpa": 7.1,
      "codingScore": 9.8,
      "communicationScore": 7.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024573,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 17.7,
      "cgpa": 7.8,
      "codingScore": 9.4,
      "communicationScore": 7.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024574,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.3,
      "cgpa": 7.7,
      "codingScore": 8.7,
      "communicationScore": 5.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024575,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 23.5,
      "cgpa": 8.7,
      "codingScore": 8.8,
      "communicationScore": 8.6,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024576,
      "year": 2026,
      "branch": "AIML",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.6,
      "codingScore": 8.1,
      "communicationScore": 5.6,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024577,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.1,
      "codingScore": 8.2,
      "communicationScore": 9.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024578,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 30.3,
      "cgpa": 9.2,
      "codingScore": 9.8,
      "communicationScore": 6.5,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024579,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 26.1,
      "cgpa": 9.4,
      "codingScore": 9.8,
      "communicationScore": 6.0,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024580,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 24.1,
      "cgpa": 9.0,
      "codingScore": 9.8,
      "communicationScore": 6.3,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024581,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 8.4,
      "cgpa": 7.8,
      "codingScore": 9.5,
      "communicationScore": 5.5,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024582,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.5,
      "codingScore": 8.5,
      "communicationScore": 8.8,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024583,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.7,
      "codingScore": 8.8,
      "communicationScore": 8.3,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024584,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 11.3,
      "cgpa": 8.5,
      "codingScore": 7.8,
      "communicationScore": 8.5,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024585,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 22.3,
      "cgpa": 9.0,
      "codingScore": 8.7,
      "communicationScore": 5.3,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024586,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 29.6,
      "cgpa": 9.3,
      "codingScore": 8.8,
      "communicationScore": 5.6,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024587,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 12.1,
      "cgpa": 9.3,
      "codingScore": 7.8,
      "communicationScore": 8.9,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024588,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 10.7,
      "cgpa": 8.0,
      "codingScore": 9.2,
      "communicationScore": 8.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024589,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 7.3,
      "communicationScore": 8.4,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024590,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.5,
      "codingScore": 7.3,
      "communicationScore": 7.5,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024591,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 8.9,
      "cgpa": 7.0,
      "codingScore": 9.2,
      "communicationScore": 7.0,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024592,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 16.0,
      "cgpa": 8.8,
      "codingScore": 9.8,
      "communicationScore": 6.5,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024593,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 11.1,
      "cgpa": 8.1,
      "codingScore": 8.5,
      "communicationScore": 6.8,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024594,
      "year": 2026,
      "branch": "IT",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 14.8,
      "cgpa": 9.3,
      "codingScore": 8.4,
      "communicationScore": 5.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024595,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.7,
      "codingScore": 6.8,
      "communicationScore": 8.9,
      "internships": 2,
      "backlogs": 1
    },
    {
      "sourceId": 2024596,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 27.3,
      "cgpa": 9.6,
      "codingScore": 9.8,
      "communicationScore": 5.8,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024597,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 30.5,
      "cgpa": 9.4,
      "codingScore": 8.3,
      "communicationScore": 8.9,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024598,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 6.1,
      "cgpa": 7.3,
      "codingScore": 9.3,
      "communicationScore": 7.2,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024599,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 14.8,
      "cgpa": 8.3,
      "codingScore": 9.8,
      "communicationScore": 8.4,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024600,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.1,
      "codingScore": 8.2,
      "communicationScore": 5.4,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024601,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 19.3,
      "cgpa": 9.5,
      "codingScore": 9.1,
      "communicationScore": 5.4,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024602,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 30.4,
      "cgpa": 8.7,
      "codingScore": 8.9,
      "communicationScore": 6.0,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024603,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 13.9,
      "cgpa": 8.0,
      "codingScore": 8.6,
      "communicationScore": 8.3,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024604,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 14.3,
      "cgpa": 7.9,
      "codingScore": 9.1,
      "communicationScore": 7.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024605,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 8.0,
      "codingScore": 8.3,
      "communicationScore": 5.6,
      "internships": 0,
      "backlogs": 1
    },
    {
      "sourceId": 2024606,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.3,
      "codingScore": 7.0,
      "communicationScore": 6.0,
      "internships": 1,
      "backlogs": 3
    },
    {
      "sourceId": 2024607,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 14.3,
      "cgpa": 8.9,
      "codingScore": 9.8,
      "communicationScore": 7.6,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024608,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.6,
      "codingScore": 7.8,
      "communicationScore": 6.2,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024609,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 31.3,
      "cgpa": 9.6,
      "codingScore": 9.8,
      "communicationScore": 8.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024610,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 27.1,
      "cgpa": 8.8,
      "codingScore": 9.8,
      "communicationScore": 7.6,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024611,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 19.5,
      "cgpa": 8.6,
      "codingScore": 8.0,
      "communicationScore": 5.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024612,
      "year": 2026,
      "branch": "IT",
      "gender": "Female",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.4,
      "codingScore": 7.2,
      "communicationScore": 8.8,
      "internships": 0,
      "backlogs": 3
    },
    {
      "sourceId": 2024613,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 40.1,
      "cgpa": 9.3,
      "codingScore": 9.6,
      "communicationScore": 5.8,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024614,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 12.1,
      "cgpa": 8.2,
      "codingScore": 8.6,
      "communicationScore": 5.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024615,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 9.4,
      "cgpa": 7.2,
      "codingScore": 8.9,
      "communicationScore": 5.9,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024616,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 10.2,
      "cgpa": 8.4,
      "codingScore": 9.5,
      "communicationScore": 9.0,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024617,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.3,
      "codingScore": 8.8,
      "communicationScore": 5.3,
      "internships": 1,
      "backlogs": 2
    },
    {
      "sourceId": 2024618,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Python",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 36.4,
      "cgpa": 9.0,
      "codingScore": 8.4,
      "communicationScore": 6.1,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024619,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 31.7,
      "cgpa": 9.2,
      "codingScore": 8.1,
      "communicationScore": 8.9,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024620,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 18.8,
      "cgpa": 8.6,
      "codingScore": 9.8,
      "communicationScore": 7.6,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024621,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Java",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 23.0,
      "cgpa": 8.9,
      "codingScore": 8.5,
      "communicationScore": 9.1,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024622,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 9.1,
      "cgpa": 7.7,
      "codingScore": 7.9,
      "communicationScore": 7.2,
      "internships": 3,
      "backlogs": 0
    },
    {
      "sourceId": 2024623,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.9,
      "codingScore": 7.8,
      "communicationScore": 8.1,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024624,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "SQL",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 29.6,
      "cgpa": 8.6,
      "codingScore": 8.4,
      "communicationScore": 6.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024625,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 6.5,
      "codingScore": 7.4,
      "communicationScore": 7.4,
      "internships": 1,
      "backlogs": 1
    },
    {
      "sourceId": 2024626,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 6.9,
      "cgpa": 7.1,
      "codingScore": 9.8,
      "communicationScore": 5.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024627,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "AIML",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 15.6,
      "cgpa": 7.7,
      "codingScore": 8.9,
      "communicationScore": 6.4,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024628,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 24.6,
      "cgpa": 9.1,
      "codingScore": 8.4,
      "communicationScore": 5.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024629,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 0,
      "placed_label": "Not placed",
      "salary_lpa": 0.0,
      "cgpa": 7.4,
      "codingScore": 7.8,
      "communicationScore": 5.6,
      "internships": 0,
      "backlogs": 0
    },
    {
      "sourceId": 2024630,
      "year": 2026,
      "branch": "CSM",
      "gender": "Male",
      "skillCategory": "Data Visualization",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 6.8,
      "cgpa": 7.2,
      "codingScore": 9.7,
      "communicationScore": 6.4,
      "internships": 2,
      "backlogs": 0
    },
    {
      "sourceId": 2024631,
      "year": 2026,
      "branch": "CSM",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 37.6,
      "cgpa": 9.0,
      "codingScore": 9.2,
      "communicationScore": 5.5,
      "internships": 1,
      "backlogs": 0
    },
    {
      "sourceId": 2024632,
      "year": 2026,
      "branch": "CSM",
      "gender": "Female",
      "skillCategory": "C",
      "placed": 1,
      "placed_label": "Placed",
      "salary_lpa": 17.4,
      "cgpa": 8.9,
      "codingScore": 8.0,
      "communicationScore": 8.4,
      "internships": 0,
      "backlogs": 0
    }
  ]
};
